OLANG = /opt/voc/bin/voc.exe

all:
	#cd build && $(OLANG) -Fs  -OC ../src/ORC.mod
	cd build && $(OLANG) -Fs  -OC ../src/ORS.mod
	cd build && $(OLANG) -Fs  -OC ../src/ORB.mod
	cd build && $(OLANG) -Fs  -OC ../src/ORG.mod
	cd build && $(OLANG) -Fs  -OC ../src/ORTool.mod
	cd build && $(OLANG) -FsM -OC ../src/ORP.mod
