O7 = ../../bootstrap-compiler/build/ORP.exe

all:
	rm -f build/*.rsc build/*.smb
	cd build && $(O7) ../src/Kernel.Mod.txt
	cd build && $(O7) ../src/Math.Mod.txt
	cd build && $(O7) ../src/Display.Mod.txt
	cd build && $(O7) ../src/Input.Mod.txt
	cd build && $(O7) ../src/PIO.Mod.txt
	cd build && $(O7) ../src/RS232.Mod.txt
	cd build && $(O7) ../src/SCC.Mod.txt
	cd build && $(O7) ../src/FileDir.Mod.txt
	cd build && $(O7) ../src/Files.Mod.txt
	cd build && $(O7) ../src/Fonts.Mod.txt
	cd build && $(O7) ../src/Modules.Mod.txt
	cd build && $(O7) ../src/Texts.Mod.txt
	cd build && $(O7) ../src/Viewers.Mod.txt
	cd build && $(O7) ../src/Oberon.Mod.txt
	cd build && $(O7) ../src/MenuViewers.Mod.txt
	cd build && $(O7) ../src/TextFrames.Mod.txt
	cd build && $(O7) ../src/System.Mod.txt

	cd build && $(O7) ../src/ORS.Mod.txt
	cd build && $(O7) ../src/ORB.Mod.txt
	cd build && $(O7) ../src/ORTool.Mod.txt
	cd build && $(O7) ../src/ORG.Mod.txt
	cd build && $(O7) ../src/ORP.Mod.txt

	cd build && $(O7) ../src/Edit.Mod.txt
	cd build && $(O7) ../src/Graphics.Mod.txt
	cd build && $(O7) ../src/GraphicFrames.Mod.txt
	cd build && $(O7) ../src/Rectangles.Mod.txt
	cd build && $(O7) ../src/Curves.Mod.txt
	cd build && $(O7) ../src/Draw.Mod.txt
	cd build && $(O7) ../src/MacroTool.Mod.txt

	cd build && $(O7) ../src/Tools.Mod.txt
	cd build && $(O7) ../src/GraphTool.Mod.txt
	cd build && $(O7) ../src/Net.Mod.txt
	cd build && $(O7) ../src/PCLink1.Mod.txt

	cd build && $(O7) ../src/EBNF.Mod.txt
	cd build && $(O7) ../src/Blink.Mod.txt
	cd build && $(O7) ../src/Checkers.Mod.txt
	cd build && $(O7) ../src/Stars.Mod.txt
	cd build && $(O7) ../src/Hilbert.Mod.txt
	cd build && $(O7) ../src/Sierpinski.Mod.txt

unused: # Not up to date
	#cd build && $(O7) ../src/ORC.Mod.txt
	#cd build && $(O7) ../src/RISC.Mod.txt


none: # Multiple sources in one file - not supported
	cd build && $(O7) ../src/SmallPrograms.Mod.txt
	cd build && $(O7) ../src/BootLoad.Mod.txt




# SmallPrograms.Mod.txt:4:  IMPORT SYSTEM, Oberon;
# SmallPrograms.Mod.txt:26:  IMPORT Texts, Oberon;
# SmallPrograms.Mod.txt:61:  IMPORT Texts, Oberon;
# SmallPrograms.Mod.txt:94:  IMPORT Texts, Oberon;
# SmallPrograms.Mod.txt:136:  IMPORT Texts, Oberon;
# SmallPrograms.Mod.txt:170:  IMPORT Texts, Oberon;
# SmallPrograms.Mod.txt:215:  IMPORT Texts, Oberon;

# BootLoad.Mod.txt:5:  IMPORT SYSTEM;
# BootLoad.Mod.txt:122:  IMPORT SYSTEM;
# BootLoad.Mod.txt:183:  IMPORT SYSTEM;

# Draw.tool
# OberonSyntax.text
# System.tool












































